services:
  extract_acte:
    build:
      context: .
      dockerfile: shared/Docker/Dockerfile_local
    environment:
      - OCR_IMAGE_SECRET_ACCESS=${OCR_IMAGE_SECRET_ACCESS}
      - OCR_IMAGE_ACCESS_KEY_ID=${OCR_IMAGE_ACCESS_KEY_ID}
      - RD_WEMBLEE_USERNAME=${RD_WEMBLEE_USERNAME}
      - RD_WEMBLEE_PASSWORD=${RD_WEMBLEE_PASSWORD}
      - RD_WEMBLEE_URL=${RD_WEMBLEE_URL}
      - UST_CONNECTOR_ACCESS_KEY_ID=${UST_CONNECTOR_ACCESS_KEY_ID}
      - UST_CONNECTOR_SECRET_ACCESS=${UST_CONNECTOR_SECRET_ACCESS}
      - UST_CONNECTOR_AWS_REGION=${UST_CONNECTOR_AWS_REGION}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ORGANIZATION=${OPENAI_ORGANIZATION}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - MISTRALAI_MODEL=${MISTRALAI_MODEL}
      - AMAZON_REGION=${AMAZON_REGION}
      - AWS_SECRETMANAGER_NAME=${AWS_SECRETMANAGER_NAME}
      - AWS_SECRETMANAGER_KEY=${AWS_SECRETMANAGER_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - OPEN_SEARCH_URL=${OPEN_SEARCH_URL}
      - OPEN_SEARCH_AUTH=${OPEN_SEARCH_AUTH}
      - OPEN_SEARCH_INDEX=${OPEN_SEARCH_INDEX}
      - LOCAL_ENVIRONMENT=${LOCAL_ENVIRONMENT}
      - APP_DIR=${APP_DIR}
      - PORT_EXPOSED=${PORT_EXPOSED}
    ports:
      - "${PORT_EXPOSED}:${PORT_EXPOSED}"
    volumes:
      - .:/extract_acte